#!/bin/bash

# This script prints the absolute path name of the current working directory

# Get the absolute path of the current working directory
current_directory=$(pwd)

# Print the absolute path name
echo "$current_directory"

